version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    ports:
      - "8090:8080"
    volumes:
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
    command:
      - start-dev
      - --import-realm
